# Generated by ChatGPT backend patch for E-Readathon library
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('program', models.CharField(choices=[('e-readathon', 'E-Readathon'), ('general', 'General Library')], default='e-readathon', max_length=80)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/')),
                ('external_url', models.URLField(blank=True)),
                ('reading_level', models.CharField(blank=True, max_length=100)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.FloatField(default=0)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('reading_minutes', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_records', to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
