# Generated by Django 5.2.14 on 2026-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
