# Generated by Django 5.2.14 on 2026-06-02 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_readathon_reports_interventions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='tutor', max_length=80)),
                ('module', models.CharField(default='general', max_length=80)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ELabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='Science Fair', max_length=120)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('research', 'Research'), ('prototype', 'Prototype'), ('testing', 'Testing'), ('report', 'Report'), ('pitch', 'Pitch'), ('completed', 'Completed')], default='idea', max_length=30)),
                ('materials', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('innovation_score', models.PositiveIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_elab_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ELabMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=40)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.elabproject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('career_matches', models.JSONField(blank=True, default=list)),
                ('learning_style', models.CharField(blank=True, max_length=120)),
                ('innovation_score', models.PositiveIntegerField(default=0)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
