# Generated by ChatGPT backend alignment patch
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_aichatlog_elabproject_elabmilestone_studentaiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericresource',
            name='resource_type',
            field=models.CharField(choices=[('task', 'Task'), ('note', 'Note'), ('discussion', 'Discussion'), ('assignment', 'Assignment'), ('grade', 'Grade'), ('event', 'Event'), ('study_group', 'Study Group'), ('career_session', 'Career Session'), ('feedback', 'Feedback'), ('support_request', 'Support Request'), ('book', 'Book'), ('my_book', 'My Book'), ('achievement', 'Achievement'), ('notification', 'Notification'), ('subscription', 'Subscription'), ('lab_project', 'Lab Project'), ('school_os', 'Efunza School OS')], max_length=50),
        ),
    ]
