# Generated by Django 5.2.14 on 2026-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_school_os_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
