# Generated by Django 5.2.14 on 2026-08-09 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coupon_product_address_cart_order_couponusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritimeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('summary', models.TextField(blank=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('track', models.CharField(choices=[('deck', 'Deck Officer'), ('engine', 'Engine Officer'), ('rating', 'Rating'), ('general', 'General Maritime')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['track', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, help_text='PDF file for the book (for Readathon display)', null=True, upload_to='books/pdfs/'),
        ),
        migrations.CreateModel(
            name='MaritimeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.CharField(choices=[('deck', 'Deck Officer'), ('engine', 'Engine Officer'), ('rating', 'Rating'), ('general', 'General Maritime')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.maritimecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maritime_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
