# Generated by Django 5.2.14 on 2026-08-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_maritimecourse_book_pdf_maritimeenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritimeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text / HTML'), ('video', 'Video URL'), ('file', 'File upload'), ('link', 'External Link')], default='text', max_length=20)),
                ('body', models.TextField(blank=True, help_text='Use for text or HTML content')),
                ('file', models.FileField(blank=True, null=True, upload_to='maritime_contents/')),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.maritimecourse')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'order'], name='api_maritim_course__714889_idx')],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
