# Generated by Django 5.2.14 on 2026-08-10 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_maritimecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maritimecourse',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='access_code_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=32),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='maritimeenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending verification'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
