# Generated by Django 5.2.14 on 2026-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_maritimecourse_fee_maritimeenrollment_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maritimeenrollment',
            name='access_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maritimeenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending verification'), ('awaiting_activation', 'Awaiting activation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
