# Generated by Django 5.2.14 on 2026-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_maritimeenrollment_access_code_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maritimeenrollment',
            name='access_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maritimeenrollment',
            name='access_code_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='maritimeenrollment',
            name='access_code',
            field=models.CharField(blank=True, help_text='LEGACY plaintext (optional)', max_length=64),
        ),
    ]
