"""
Django settings for efunza_backend project.
Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
import os
import sys

# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# CORE SETTINGS
# ============================================================

SECRET_KEY = config('SECRET_KEY', default='dev-key-change-in-production')
DEBUG = config('DEBUG', default=True, cast=bool)
ENVIRONMENT = config('ENVIRONMENT', default='development')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

# ============================================================
# INSTALLED APPS
# ============================================================

INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'storages',  # For AWS S3 (optional)
    'django_celery_results',  # For Celery task results
    
    # Efunza Apps
    'api',
    'intelligence',  # Efunza Intelligence Engine
    'knowledge_graph',  # Knowledge Graph
    'evidence',  # Evidence & Competency
]

# ============================================================
# MIDDLEWARE - CORS MUST BE EARLY
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'efunza_backend.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ]
    }
}]

WSGI_APPLICATION = 'efunza_backend.wsgi.application'

# ============================================================
# DATABASE
# ============================================================

import dj_database_url

DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=config('DB_SSL_REQUIRE', default=True, cast=bool)
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3'
        }
    }

# ============================================================
# AUTHENTICATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'auth.User'

# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC & MEDIA FILES
# ============================================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATICFILES_DIRS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# AWS S3 (Optional - for production file storage)
# ============================================================

USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3 and not DEBUG:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_VERIFY = True
    
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    AWS_STATIC_LOCATION = 'static'
    AWS_MEDIA_LOCATION = 'media'
    
    STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/{AWS_STATIC_LOCATION}/'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/{AWS_MEDIA_LOCATION}/'

# ============================================================
# 🚀 CORS CONFIGURATION - COMPLETE FIX
# ============================================================

# In production, never use CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = False

# ✅ Add ALL your frontend domains here
CORS_ALLOWED_ORIGINS = [
    # Development
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    # Production - Backend
    'https://efunza.jamelecinnovations.com',
    # Production - Frontend
    'https://efunzaapp.jamelecinnovations.com',
    # Additional domains
    'https://efunza.com',
    'https://www.efunza.com',
]

# Add allowed origins from environment
CORS_ALLOWED_ORIGINS += config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

# ✅ Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# ✅ Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'access-control-allow-credentials',
    'content-disposition',
    'x-api-key',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_PREFLIGHT_MAX_AGE = 86400

# ✅ CSRF Trusted Origins (for forms)
CSRF_TRUSTED_ORIGINS = [
    'https://efunza.jamelecinnovations.com',
    'https://efunzaapp.jamelecinnovations.com',
]

# ============================================================
# REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

    # Throttling - protect endpoints like claim_code
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '100/day',
        # Scoped throttle for claim_code (view-level throttle can use scope 'claim_code' if needed)
        'claim_code': '6/minute',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# ============================================================
# OPENAI
# ============================================================

OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4o-mini')
OPENAI_EMBEDDING_MODEL = config('OPENAI_EMBEDDING_MODEL', default='text-embedding-3-small')
OPENAI_MAX_TOKENS = config('OPENAI_MAX_TOKENS', default=2000, cast=int)
OPENAI_TEMPERATURE = config('OPENAI_TEMPERATURE', default=0.7, cast=float)

# ============================================================
# INTELLIGENCE ENGINE CONFIGURATION
# ============================================================

# Mastery Engine Settings
MASTERY_CONFIG = {
    'THRESHOLD': config('INTELLIGENCE_MASTERY_THRESHOLD', default=0.7, cast=float),
    'DECAY_HALF_LIFE': config('INTELLIGENCE_DECAY_HALF_LIFE', default=30, cast=int),
    'MIN_ATTEMPTS': config('INTELLIGENCE_MIN_ATTEMPTS', default=3, cast=int),
    'EVIDENCE_BOOST_MAX': 0.15,
    'CONSISTENCY_THRESHOLD': 0.7,
}

# Action Engine Settings
ACTION_CONFIG = {
    'LEARN_PRIORITY': 7,
    'REMEDIATE_PRIORITY': 10,
    'PRACTICE_PRIORITY': 6,
    'REASSESS_PRIORITY': 5,
    'SIMULATE_PRIORITY': 8,
    'BUILD_PRIORITY': 7,
    'CHALLENGE_PRIORITY': 4,
    'ADVANCE_PRIORITY': 9,
}

# RAG Settings
RAG_CONFIG = {
    'MAX_RESULTS': 10,
    'MIN_RELEVANCE_SCORE': 0.3,
    'USE_LEARNER_CONTEXT': True,
    'CONTEXT_WEIGHT': 0.6,
}

# Evidence Settings
EVIDENCE_CONFIG = {
    'AUTO_VERIFY_THRESHOLD': 0.9,
    'HIGH_STAKES_TYPES': ['exam', 'project', 'internship', 'certification'],
    'EVIDENCE_EXPIRY_DAYS': 365,
}

# Closed Loop Settings
CLOSED_LOOP_CONFIG = {
    'ENABLED': config('ENABLE_CLOSED_LOOP', default=True, cast=bool),
    'ASYNC_PROCESSING': config('INTELLIGENCE_ENABLE_ASYNC', default=False, cast=bool),
    'CACHE_TIMEOUT': 3600,
    'MAX_HISTORY': 100,
}

# Intelligence Feature Flags
INTELLIGENCE_FEATURES = {
    'ENABLE_MASTERY_ENGINE': config('ENABLE_MASTERY_ENGINE', default=True, cast=bool),
    'ENABLE_ACTION_ENGINE': config('ENABLE_ACTION_ENGINE', default=True, cast=bool),
    'ENABLE_RAG_SERVICE': config('ENABLE_RAG_SERVICE', default=True, cast=bool),
    'ENABLE_EVIDENCE_TRACKING': config('ENABLE_EVIDENCE_TRACKING', default=True, cast=bool),
    'ENABLE_COMPETENCY_ENGINE': config('ENABLE_COMPETENCY_ENGINE', default=True, cast=bool),
    'ENABLE_LEARNING_PATH': config('ENABLE_LEARNING_PATH', default=True, cast=bool),
    'ENABLE_ANALYTICS': config('ENABLE_ANALYTICS', default=True, cast=bool),
    'ENABLE_CLOSED_LOOP': config('ENABLE_CLOSED_LOOP', default=True, cast=bool),
    'ENABLE_ADAPTIVE_ASSESSMENTS': config('ENABLE_ADAPTIVE_ASSESSMENTS', default=True, cast=bool),
}

# ============================================================
# CELERY CONFIGURATION (Optional - for async processing)
# ============================================================

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_RESULT_EXTENDED = True
CELERY_TASK_ALWAYS_EAGER = DEBUG  # Run tasks synchronously in debug

# ============================================================
# CACHING (Enhanced for Intelligence Engine)
# ============================================================

# Create logs directory
LOG_DIR = BASE_DIR / 'logs'
if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True, exist_ok=True)

# Cache configuration
if config('REDIS_URL', default=None) and not DEBUG:
    # Production Redis Cache
    REDIS_URL = config('REDIS_URL')
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PARSER_CLASS': 'redis.connection.HiredisParser',
                'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
                'CONNECTION_POOL_CLASS_KWARGS': {
                    'max_connections': 50,
                    'timeout': 20,
                },
                'MAX_CONNECTIONS': 1000,
                'PICKLE_VERSION': -1,
            },
            'KEY_PREFIX': 'efunza',
        },
        'intelligence': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PARSER_CLASS': 'redis.connection.HiredisParser',
                'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
                'CONNECTION_POOL_CLASS_KWARGS': {
                    'max_connections': 50,
                    'timeout': 20,
                },
                'MAX_CONNECTIONS': 1000,
                'PICKLE_VERSION': -1,
            },
            'KEY_PREFIX': 'efunza_intelligence',
            'TIMEOUT': 3600,
        }
    }
else:
    # Development Local Memory Cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'efunza_default_cache',
        },
        'intelligence': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'efunza_intelligence_cache',
            'TIMEOUT': 3600,
        }
    }

# ============================================================
# LOGGING CONFIGURATION (Enhanced for Intelligence Engine)
# ============================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'intelligence': {
            'format': '[{levelname}] {asctime} - {name} - {message}',
            'style': '{',
        },
        'json': {
            'format': '{"level": "{levelname}", "time": "{asctime}", "module": "{module}", "message": "{message}"}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': sys.stdout,
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'intelligence_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'intelligence.log',
            'formatter': 'intelligence',
        },
        'mastery_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'mastery_engine.log',
            'formatter': 'intelligence',
        },
        'evidence_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'evidence.log',
            'formatter': 'intelligence',
        },
        'closed_loop_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'closed_loop.log',
            'formatter': 'intelligence',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        # Production handlers
        'sentry': {
            'class': 'sentry_sdk.integrations.logging.EventHandler',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'intelligence': {
            'handlers': ['console', 'intelligence_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'intelligence.engines': {
            'handlers': ['console', 'mastery_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'intelligence.services': {
            'handlers': ['console', 'closed_loop_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'evidence': {
            'handlers': ['console', 'evidence_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'knowledge_graph': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Add Sentry if configured
SENTRY_DSN = config('SENTRY_DSN', default=None)
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=0.1,
        send_default_pii=True,
        environment=ENVIRONMENT,
    )
    
    # Add Sentry to logging
    if 'sentry' not in LOGGING['handlers']:
        LOGGING['handlers']['sentry'] = {
            'class': 'sentry_sdk.integrations.logging.EventHandler',
            'level': 'ERROR',
        }
    
    # Add Sentry to Django logger
    LOGGING['loggers']['django']['handlers'].append('sentry')
    LOGGING['loggers']['intelligence']['handlers'].append('sentry')
    LOGGING['loggers']['evidence']['handlers'].append('sentry')

# ============================================================
# SECURITY SETTINGS (Production)
# ============================================================

if not DEBUG:
    # HTTPS Settings
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Session Settings
    SESSION_COOKIE_AGE = 86400  # 24 hours
    SESSION_SAVE_EVERY_REQUEST = True
    
    # CSRF Settings
    CSRF_COOKIE_HTTPONLY = True
    CSRF_USE_SESSIONS = True

# ============================================================
# EMAIL CONFIGURATION
# ============================================================

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@efunza.com')

# ============================================================
# MISC SETTINGS
# ============================================================

# API Settings
API_VERSION = config('API_VERSION', default='v1')
API_PREFIX = f'/api/{API_VERSION}'

# Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Celery Beat Schedule (for scheduled tasks)
if not DEBUG:
    CELERY_BEAT_SCHEDULE = {
        'update-mastery-daily': {
            'task': 'intelligence.tasks.update_all_mastery',
            'schedule': 86400,  # Every 24 hours
        },
        'process-pending-evidence': {
            'task': 'intelligence.tasks.process_pending_evidence',
            'schedule': 3600,  # Every hour
        },
        'generate-analytics-weekly': {
            'task': 'intelligence.tasks.generate_weekly_analytics',
            'schedule': 604800,  # Every week
        },
    }

# ============================================================
# INTELLIGENCE ENGINE INITIALIZATION
# ============================================================

# This ensures that the intelligence engine is ready when Django starts
# The signals.py file will handle auto-creation of profiles

# ============================================================
# DEBUG TOOLBAR (Development only)
# ============================================================

if DEBUG:
    try:
        import debug_toolbar
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1', 'localhost']
    except ImportError:
        pass

# ============================================================
# SYSTEM CHECK OVERRIDES
# ============================================================

# Silence some warnings in development
SILENCED_SYSTEM_CHECKS = [
    'fields.W342',  # Foreign key with unique constraint
    'security.W004',  # SECURE_HSTS_SECONDS
]

print(f"✅ Efunza Backend v{API_VERSION} loaded | Environment: {ENVIRONMENT} | Debug: {DEBUG}")
